inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'db/**/*'

Metrics/MethodLength:
  Max: 16
  Exclude:
    - 'db/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'

Style/DotPosition:
  EnforcedStyle: trailing

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/Output:
  Exclude:
    - 'db/seeds.rb'
    - 'lib/export_qr_codes.rb'
    - 'lib/get_your_rep/get_all_the_reps.rb'
    - 'lib/import_qr_codes.rb'
    - 'lib/shapefiles.rb'